### ISSUE TITLE
Test it for various timeouts

### ISSUE THREAD

**Issue by seletskiy** [kovetskiy/pam_eye#1]
I'm interested in how it will behave under following conditions:
- no response from DNS (e.g. name can't be resolved);
- resolve successfull, but TCP connection can't be established;
- TCP connection is ok, but TCP session hangs in the middle of request;
- TCP request has been sent, but TCP session hangs at reply from server (BTW, pam_eye should not wait for reply in any case; send and close the connection, do not wait for answer!).

**Comment by kovetskiy** [comment]
> no response from DNS (e.g. name can't be resolved);
> resolve successfull, but TCP connection can't be established;
> TCP connection is ok, but TCP session hangs in the middle of request;

curl timeout works on full request time (dns resolve, connect, send, receive), so if any error occurred and time spent on request more than 10seconds, connection will be closed.
In all cases pam_eye do not crashes user authorization.

> BTW, pam_eye should not wait for reply in any case; send and close the connection, do not wait for answer

I think about it, but I don't see any problem in send-receive scheme, and with curl it's not trivial issue. So, if there is a real problem, then yes. BTW (how you like) pull-requests are welcome
